### ISSUE TITLE
CMake issue with add_llvm_library

### ISSUE THREAD

**Issue by sebastiankreutzer** [kavon/atJIT#15]
I get a CMake error when trying to build atJIT with the following configuration:
`cmake -DCMAKE_INSTALL_PREFIX=/opt/packages/atjit/atjit -DPOLLY_KNOBS=ON -DLLVM_ROOT=/opt/packages/atjit/llvm/install ..`

I'm running on Ubuntu 18.10. I have tried CMake 3.8.2 and 3.13.2, both versions produce the same error. I used the `get-llvm-with-polly.sh` script to build LLVM and Polly.

Full CMake output:

> -- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 8.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type: Release
-- Found LLVM 8.0.0svn
-- Using LLVMConfig.cmake in /opt/packages/atjit/llvm/install/lib/cmake/llvm
-- LLVM dylib: ON
-- LLVM RTTI: ON
-- Polly Knobs: ON
-- Linker detection: GNU ld
CMake Error at /opt/packages/atjit/llvm/install/lib/cmake/llvm/AddLLVM.cmake:657 (install):
  install TARGETS given no LIBRARY DESTINATION for module target
  "EasyJitPass".
Call Stack (most recent call first):
  pass/CMakeLists.txt:8 (add_llvm_library)
-- Found XGB_LIB: /home/sebastian/git/atJIT/xgboost/root/lib/libxgboost.so
-- Found XGB_INCLUDE_DIR: /home/sebastian/git/atJIT/xgboost/root/include
-- Found RABIT_INCLUDE_DIR: /home/sebastian/git/atJIT/xgboost/root/rabit/include
-- Found DMLC_INCLUDE_DIR: /home/sebastian/git/atJIT/xgboost/root/dmlc-core/include
-- Found XGB_LIB_DIR: /home/sebastian/git/atJIT/xgboost/root/lib
-- Found GCD_LIB: /usr/lib/libdispatch.so
-- Found GCD_INCLUDE_DIR: /usr/include
-- Using PollyConfig.cmake in /opt/packages/atjit/llvm/install/lib/cmake/polly
-- Could NOT find PY_lit (missing:  PY_LIT) 
-- Found VALGRIND_EXE: /usr/bin/valgrind
-- Configuring incomplete, errors occurred!

**Comment by kavon** [comment]
Looks like Kruse's version of LLVM + Clang + Polly that is being checked out by that script is broken, and this wasn't caught by CI because I forgot to add it. The LLVM 8 upgrade happened while I moved to a new CI system with more resources. I updated the commits to the latest version of all 3 repos in 6a0f76175c6bd3b9c243aab01b67f613ba486184 and it still is broken with this:

```
CMake Error at cmake/modules/AddLLVM.cmake:657 (install):
  install TARGETS given no LIBRARY DESTINATION for module target
  "CheckerOptionHandlingAnalyzerPlugin".
Call Stack (most recent call first):
  tools/clang/test/Analysis/plugins/CheckerOptionHandling/CMakeLists.txt:2 (add_llvm_library)
```

Because the ability to tune Polly depends on extensions only in Kruse's branch, for now I suggest checking out and building LLVM + Clang 8 release versions and passing `-DPOLLY_KNOBS=OFF` to cmake. Specifically, the CI is testing against a locally built version of git tag `llvmorg-8.0.0`: https://gitlab.com/kavon1/atJIT/-/jobs/211646534
